a = float(input("Podaj pierwszą liczbę: "))
b = float(input("Podaj drugą liczbę: "))

print('Suma liczb wynosi:', a + b)
print('Różnica liczb wynosi:', a - b)
print('Iloczyn liczb wynosi:', a * b)
print('Iloraz liczb wynosi:', a / b)
print('Reszta z dzielenia wynosi:', a % b)
print('Całkowita część z dzielenia wynosi:', a // b)
print('Potęga wynosi:', a ** b)
